# Generated by Django 5.0.6 on 2025-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair')], default='dark', max_length=10),
        ),
    ]
