# Generated by Django 5.0.6 on 2025-12-19 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_ui_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=180)),
                ('pn', models.CharField(blank=True, default='', max_length=64)),
                ('pn_mfr', models.CharField(blank=True, default='', max_length=64)),
                ('ata', models.CharField(blank=True, default='', max_length=16)),
                ('barcode', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='accounts.organization')),
                ('locations', models.ManyToManyField(blank=True, related_name='items', to='stock.stocklocation')),
            ],
            options={
                'ordering': ['designation', 'pn'],
            },
        ),
    ]
