# Generated by Django 5.0.6 on 2025-11-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='initial_cycles',
            field=models.PositiveIntegerField(default=0, verbose_name='Cycles initiaux'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='initial_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='HDV initiales (minutes)'),
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('from_icao', models.CharField(blank=True, max_length=8, verbose_name='Départ (ICAO/IATA)')),
                ('to_icao', models.CharField(blank=True, max_length=8, verbose_name='Arrivée (ICAO/IATA)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('cycles', models.PositiveSmallIntegerField(default=1, verbose_name='Cycles')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fleet.aircraft')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
