# Generated by Django 5.0.6 on 2025-11-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_aircraft_initial_cycles_aircraft_initial_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la visite')),
                ('interval_minutes', models.PositiveIntegerField(help_text='Ex: 50h = 3000', verbose_name='Intervalle (minutes)')),
                ('interval_cycles', models.PositiveIntegerField(default=0, help_text='Optionnel (0 si non utilisé)', verbose_name='Intervalle (cycles)')),
                ('due_at_minutes', models.PositiveIntegerField(verbose_name='Échéance actuelle (minutes totales cellule)')),
                ('due_at_cycles', models.PositiveIntegerField(default=0, verbose_name='Échéance actuelle (cycles totaux cellule)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_rules', to='fleet.aircraft')),
            ],
            options={
                'ordering': ['aircraft', 'name'],
                'unique_together': {('aircraft', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VisitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de réalisation')),
                ('at_minutes', models.PositiveIntegerField(verbose_name='Minutes totales cellule (au moment de la réalisation)')),
                ('at_cycles', models.PositiveIntegerField(default=0, verbose_name='Cycles totaux cellule (au moment de la réalisation)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='fleet.visitrule')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
