# Generated by Django 5.0.6 on 2025-12-15 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_visitrule_visitcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('airframe', 'Cellule'), ('engine', 'Moteur'), ('propeller', 'Hélice'), ('avionics', 'Avionique'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Constructeur')),
                ('part_number', models.CharField(blank=True, max_length=120, verbose_name='Part Number')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Serial Number')),
                ('initial_tsn_minutes', models.PositiveIntegerField(default=0, verbose_name='TSN initial (minutes)')),
                ('initial_csn_cycles', models.PositiveIntegerField(default=0, verbose_name='CSN initial (cycles)')),
                ('limit_minutes', models.PositiveIntegerField(default=0, verbose_name='Limite (minutes)')),
                ('limit_cycles', models.PositiveIntegerField(default=0, verbose_name='Limite (cycles)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'serial_number', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Désignation')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Constructeur')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='N° de série')),
                ('part_number', models.CharField(blank=True, max_length=120, verbose_name='Part Number')),
                ('initial_minutes', models.PositiveIntegerField(default=0, verbose_name='Heures initiales (minutes)')),
                ('initial_cycles', models.PositiveIntegerField(default=0, verbose_name='Cycles initiaux')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='fleet.aircraft')),
            ],
            options={
                'ordering': ['aircraft__registration', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KardexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('install', 'Installation'), ('remove', 'Dépose'), ('inspect', 'Inspection'), ('overhaul', 'Révision')], max_length=20, verbose_name='Action')),
                ('date', models.DateField(verbose_name='Date')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Position / emplacement')),
                ('at_minutes', models.PositiveIntegerField(default=0, verbose_name='Total (minutes) au moment de l’action')),
                ('at_cycles', models.PositiveIntegerField(default=0, verbose_name='Total (cycles) au moment de l’action')),
                ('workorder_ref', models.CharField(blank=True, max_length=120, verbose_name='Référence doc / WO')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kardex_entries', to='fleet.aircraft')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kardex.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kardex_entries', to='kardex.engine')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
