# Generated by Django 5.0.6 on 2025-12-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_visitrule_visitcompletion'),
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='installed_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_components', to='fleet.aircraft'),
        ),
        migrations.AddField(
            model_name='component',
            name='installed_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_components', to='kardex.engine'),
        ),
        migrations.AddField(
            model_name='component',
            name='installed_position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Position / emplacement'),
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('stock', 'En stock'), ('installed', 'Installé'), ('in_shop', 'En maintenance'), ('scrapped', 'Réformé')], default='stock', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kardexentry',
            name='action',
            field=models.CharField(choices=[('install', 'Installation'), ('remove', 'Dépose'), ('send_shop', 'Envoi maintenance'), ('return_shop', 'Retour maintenance'), ('inspect', 'Inspection'), ('overhaul', 'Révision'), ('scrap', 'Réforme')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='kardexentry',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_entries', to='fleet.aircraft'),
        ),
        migrations.AlterField(
            model_name='kardexentry',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_entries', to='kardex.engine'),
        ),
    ]
