# Generated by Django 5.0.6 on 2025-12-16 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_component_installed_aircraft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('cycles', models.PositiveSmallIntegerField(default=0, verbose_name='Cycles')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kardex.engine')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
