# Generated by Django 5.0.6 on 2025-12-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_enginelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ata',
            field=models.CharField(blank=True, db_index=True, help_text='Ex: 24, 32, 52...', max_length=10, verbose_name='ATA'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Désignation'),
        ),
    ]
